name: Deploy to cPanel
on:
  push:
    branches: [ main ] # Jalankan setiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 163.223.227.37
          username: dzxtssbx
          port: 6401
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
        
